var level01 = new level(); //Create level.

//Create room.
var room01 = new room(0, 22, 16);
room01.room = [["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"],
			   ["d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1", "d_floor1"]];
level01.addRoom(room01);